language: php

env:
  global:
    - WP_DB_USER=wp
    - WP_DB_PASS=password
    - WP_DB_NAME=wp_tests
    - WP_TESTS_DIR=/tmp/wordpress-tests-lib
    - WP_CORE_DIR=/tmp/wordpress/
    - WP_VERSION=latest

php:
  - 7.2
  - 7.1
  - 7.0
  - 5.6

matrix:
  include:
    - php: 7.0
      env: WP_VERSION=composer # use wp-phpunit
    - php: 5.6
      env: WP_VERSION=3.7.11
    - php: 5.6
      env: WP_VERSION=trunk

before_script:
  - composer validate --strict
  - mysql -u root -e "GRANT ALL PRIVILEGES ON wp_tests.* TO wp IDENTIFIED BY 'password';"
  - if [ 'composer' != $WP_VERSION ]; then curl -sSL -o tests/install-wp-tests.sh https://github.com/wp-cli/scaffold-command/raw/04be3128e743a0d94a1db5b7da942b538e96e6a8/templates/install-wp-tests.sh; fi
  - if [ 'composer' != $WP_VERSION ]; then bash tests/bin/install-wp-tests.sh $WP_DB_NAME $WP_DB_USER $WP_DB_PASS; fi

install: if [ 'composer' == $WP_VERSION ]; then composer install; fi # install dev-dependencies

script:
  - if [ 'composer' != $WP_VERSION ]; then phpunit; fi
  - if [ 'composer' == $WP_VERSION ]; then composer test; fi
